name: csxy
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # audioplayer: ^0.5.2
  # audioplayer=C:\\Users\\Administrator\\AppData\\Roaming\\Pub\\Cache\\hosted\\pub.flutter-io.cn\\audioplayer-0.5.2\\
  audioplayers: ^0.13.2
  # 0.13.2
  sqflite: ^1.1.6
  flutter_staggered_grid_view: ^0.2.7
  path_provider: ^1.1.0
  leancloud_flutter_plugin: ^0.0.5
  #  flutter_downloader: ^1.3.1
  shared_preferences: ^0.5.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^3.0.0
  dio: ^2.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/bookcircle.png
    - images/welcomepage.png
    - images/homepagebg.png
    - images/listenbutton.png
    - images/drawable-xxhdpi/listenplaypicture1-1.png
    - images/drawable-mdpi/listenplaypicture1-1.png
    - images/drawable-xxhdpi/listeningbutton.png
    - images/drawable-xxhdpi/readingbutton.png
    - images/drawable-xxhdpi/wordbutton.png
    - images/drawable-xxhdpi/homepage_day.png
    - images/drawable-xxhdpi/homepage_night.png
    - images/drawable-xxhdpi/listenbooklistpic.png
    - images/drawable-xxhdpi/268.png
    - images/drawable-xxhdpi/271.png
    - images/drawable-xxhdpi/p1.png
    - images/drawable-xxhdpi/p2.png
    - images/drawable-xxhdpi/p22.png
    - images/drawable-xxhdpi/p29.png
    - images/drawable-xxhdpi/223.png
    - images/drawable-xxhdpi/221.png
    - images/readbutton.png
    - images/wordbutton.png
    - images/todayobjicon.png
    - images/learndayicon.png
    - images/homebackicon.png
    - images/books.png
    - images/singlewordbg.png
    - images/SpanishSyllabusVIIIVocabulary.png
    - images/animal.png
    - images/modernspanish.png
    - images/law.png
    - images/primaryvocabulary.png
    - images/fruit.png
    - images/utility.png
    - images/vocation.png
    - images/football.png
    - images/bookcircle.png
    - images/welcomepage.png
    - images/listenbutton.png
    - images/readingMenu1.jpg
    - images/readingMenu2.png
  #  - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
