// ignore: library_names
library flutter_app.Globals;

class Book{
  final String BookName;
  bool isDownloaded;
  Book(this.BookName,this.isDownloaded);
}

var WordDB;
final List booksname=['Book1','Book2'];
List<Book> BookDetailInfo=[new Book('Spanish syllabus 8 vocabulary (except for verbs)',false),new Book('DELE3000 high frequency words',false)];

class News {
  final String newsTitle;
  String chineseName;
  String shortIntroduction;
  String createTime;
  String difficulty;
  String wordNumbers;
  String source;
  String details;
  String chineseDetails;
  String downloadURL;
  News(this.newsTitle, this.chineseName, this.shortIntroduction, this.createTime, this.difficulty, this.wordNumbers, this.source, this.details, this.chineseDetails, this.downloadURL);
}

class Question {
  String questionContent;
  String question;
  String correctAnswer;
  List<String> wrongAnswer;
  Question(this.questionContent, this.question, this.correctAnswer, this.wrongAnswer);
}

String newArticle = "Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.\n\nPero el cambio climático está haciendo tales extremas más frecuentes, y los efectos no se limitan al viejo y enfermo. Las temperaturas de calentamiento no sólo amenazan vidas directamente. También causar miles de millones de horas de trabajo perdida, mejorar las condiciones para la propagación de enfermedades infecciosas y reducir el rendimiento de los cultivos, según un informe reciente.\n\nEl informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.";

List<News> NewsExample = [
  new News('El cambio climático está teniendo un impacto importante sobre la Salud Global', '气候变化正对全球健康产生巨大影响', 'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.', '2019/03/17', 'DELE A2', '235', 'Scientific American',
      'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.\n\nPero el cambio climático está haciendo tales extremas más frecuentes, y los efectos no se limitan al viejo y enfermo. Las temperaturas de calentamiento no sólo amenazan vidas directamente.\n\nTambién causar miles de millones de horas de trabajo perdida, mejorar las condiciones para la propagación de enfermedades infecciosas y reducir el rendimiento de los cultivos, según un informe reciente.\n\nEl informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.\n\nAfecta a todo el mundo todo el mundo, cada persona, cada población individual. Ningún país es inmune", dice Nick Watts, director ejecutivo de la cuenta regresiva de la lanceta y uno de muchos coautores del informe. "Nos hemos estado viendo estos impactos desde hace algún tiempo.\n\n',
      '2003年，一股毁灭性的热浪席卷了欧洲，据科学家估计，造成了成千上万的人的死亡。这其中有很多是行动不便的老年人，也有一些一直遭受慢性疾病的人。但是，气候变化正使得这样的极端天气变得越来越 常见——并且由此产生的影响将不仅危及老人和病人。据近期报道，气候变暖不仅对生命直接产生威胁，这些气候变化还会引起几亿个小时的劳动力损失，增强感染性疾病的传播条件，以及减少作物的产量。', 'www.google.com'),
  new News('El cambio climático está teniendo un impacto importante sobre la Salud Global', '气候变化正对全球健康产生巨大影响', 'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.', '2019/04/17', 'DELE A2', '235', 'Scientific American',
      'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.\nPero el cambio climático está haciendo tales extremas más frecuentes, y los efectos no se limitan al viejo y enfermo. Las temperaturas de calentamiento no sólo amenazan vidas directamente.\nTambién causar miles de millones de horas de trabajo perdida, mejorar las condiciones para la propagación de enfermedades infecciosas y reducir el rendimiento de los cultivos, según un informe reciente.\nEl informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.\nAfecta a todo el mundo todo el mundo, cada persona, cada población individual. Ningún país es inmune", dice Nick Watts, director ejecutivo de la cuenta regresiva de la lanceta y uno de muchos coautores del informe. "Nos hemos estado viendo estos impactos desde hace algún tiempo.\n',
      '2003年，一股毁灭性的热浪席卷了欧洲，据科学家估计，造成了成千上万的人的死亡。这其中有很多是行动不便的老年人，也有一些一直遭受慢性疾病的人。但是，气候变化正使得这样的极端天气变得越来越 常见——并且由此产生的影响将不仅危及老人和病人。据近期报道，气候变暖不仅对生命直接产生威胁，这些气候变化还会引起几亿个小时的劳动力损失，增强感染性疾病的传播条件，以及减少作物的产量。', 'www.google.com'),
  new News('El cambio climático está teniendo un impacto importante sobre la Salud Global', '气候变化正对全球健康产生巨大影响', 'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.', '2019/01/17', 'DELE A2', '235', 'Scientific American',
      'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.\nPero el cambio climático está haciendo tales extremas más frecuentes, y los efectos no se limitan al viejo y enfermo. Las temperaturas de calentamiento no sólo amenazan vidas directamente.\nTambién causar miles de millones de horas de trabajo perdida, mejorar las condiciones para la propagación de enfermedades infecciosas y reducir el rendimiento de los cultivos, según un informe reciente.\nEl informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.\nAfecta a todo el mundo todo el mundo, cada persona, cada población individual. Ningún país es inmune", dice Nick Watts, director ejecutivo de la cuenta regresiva de la lanceta y uno de muchos coautores del informe. "Nos hemos estado viendo estos impactos desde hace algún tiempo.\n',
      '2003年，一股毁灭性的热浪席卷了欧洲，据科学家估计，造成了成千上万的人的死亡。这其中有很多是行动不便的老年人，也有一些一直遭受慢性疾病的人。但是，气候变化正使得这样的极端天气变得越来越 常见——并且由此产生的影响将不仅危及老人和病人。据近期报道，气候变暖不仅对生命直接产生威胁，这些气候变化还会引起几亿个小时的劳动力损失，增强感染性疾病的传播条件，以及减少作物的产量。', 'www.google.com'),
  new News('El cambio climático está teniendo un impacto importante sobre la Salud Global', '气候变化正对全球健康产生巨大影响', 'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.', '2019/07/17', 'DELE A2', '235', 'Scientific American',
      'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.\nPero el cambio climático está haciendo tales extremas más frecuentes, y los efectos no se limitan al viejo y enfermo. Las temperaturas de calentamiento no sólo amenazan vidas directamente.\nTambién causar miles de millones de horas de trabajo perdida, mejorar las condiciones para la propagación de enfermedades infecciosas y reducir el rendimiento de los cultivos, según un informe reciente.\nEl informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.\nAfecta a todo el mundo todo el mundo, cada persona, cada población individual. Ningún país es inmune", dice Nick Watts, director ejecutivo de la cuenta regresiva de la lanceta y uno de muchos coautores del informe. "Nos hemos estado viendo estos impactos desde hace algún tiempo.\n',
      '2003年，一股毁灭性的热浪席卷了欧洲，据科学家估计，造成了成千上万的人的死亡。这其中有很多是行动不便的老年人，也有一些一直遭受慢性疾病的人。但是，气候变化正使得这样的极端天气变得越来越 常见——并且由此产生的影响将不仅危及老人和病人。据近期报道，气候变暖不仅对生命直接产生威胁，这些气候变化还会引起几亿个小时的劳动力损失，增强感染性疾病的传播条件，以及减少作物的产量。', 'www.google.com'),
  new News('El cambio climático está teniendo un impacto importante sobre la Salud Global', '气候变化正对全球健康产生巨大影响', 'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.', '2019/06/17', 'DELE A2', '235', 'Scientific American',
      'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.\nPero el cambio climático está haciendo tales extremas más frecuentes, y los efectos no se limitan al viejo y enfermo. Las temperaturas de calentamiento no sólo amenazan vidas directamente.\nTambién causar miles de millones de horas de trabajo perdida, mejorar las condiciones para la propagación de enfermedades infecciosas y reducir el rendimiento de los cultivos, según un informe reciente.\nEl informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.\nAfecta a todo el mundo todo el mundo, cada persona, cada población individual. Ningún país es inmune", dice Nick Watts, director ejecutivo de la cuenta regresiva de la lanceta y uno de muchos coautores del informe. "Nos hemos estado viendo estos impactos desde hace algún tiempo.\n',
      '2003年，一股毁灭性的热浪席卷了欧洲，据科学家估计，造成了成千上万的人的死亡。这其中有很多是行动不便的老年人，也有一些一直遭受慢性疾病的人。但是，气候变化正使得这样的极端天气变得越来越 常见——并且由此产生的影响将不仅危及老人和病人。据近期报道，气候变暖不仅对生命直接产生威胁，这些气候变化还会引起几亿个小时的劳动力损失，增强感染性疾病的传播条件，以及减少作物的产量。', 'www.google.com'),
  new News('El cambio climático está teniendo un impacto importante sobre la Salud Global', '气候变化正对全球健康产生巨大影响', 'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.', '2019/03/17', 'DELE A2', '235', 'Scientific American',
      'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.\nPero el cambio climático está haciendo tales extremas más frecuentes, y los efectos no se limitan al viejo y enfermo. Las temperaturas de calentamiento no sólo amenazan vidas directamente.\nTambién causar miles de millones de horas de trabajo perdida, mejorar las condiciones para la propagación de enfermedades infecciosas y reducir el rendimiento de los cultivos, según un informe reciente.\nEl informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.\nAfecta a todo el mundo todo el mundo, cada persona, cada población individual. Ningún país es inmune", dice Nick Watts, director ejecutivo de la cuenta regresiva de la lanceta y uno de muchos coautores del informe. "Nos hemos estado viendo estos impactos desde hace algún tiempo.\n',
      '2003年，一股毁灭性的热浪席卷了欧洲，据科学家估计，造成了成千上万的人的死亡。这其中有很多是行动不便的老年人，也有一些一直遭受慢性疾病的人。但是，气候变化正使得这样的极端天气变得越来越 常见——并且由此产生的影响将不仅危及老人和病人。据近期报道，气候变暖不仅对生命直接产生威胁，这些气候变化还会引起几亿个小时的劳动力损失，增强感染性疾病的传播条件，以及减少作物的产量。', 'www.google.com'),
  new News('El cambio climático está teniendo un impacto importante sobre la Salud Global', '气候变化正对全球健康产生巨大影响', 'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.', '2019/09/17', 'DELE A2', '235', 'Scientific American',
      'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.\nPero el cambio climático está haciendo tales extremas más frecuentes, y los efectos no se limitan al viejo y enfermo. Las temperaturas de calentamiento no sólo amenazan vidas directamente.\nTambién causar miles de millones de horas de trabajo perdida, mejorar las condiciones para la propagación de enfermedades infecciosas y reducir el rendimiento de los cultivos, según un informe reciente.\nEl informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.\nAfecta a todo el mundo todo el mundo, cada persona, cada población individual. Ningún país es inmune", dice Nick Watts, director ejecutivo de la cuenta regresiva de la lanceta y uno de muchos coautores del informe. "Nos hemos estado viendo estos impactos desde hace algún tiempo.\n',
      '2003年，一股毁灭性的热浪席卷了欧洲，据科学家估计，造成了成千上万的人的死亡。这其中有很多是行动不便的老年人，也有一些一直遭受慢性疾病的人。但是，气候变化正使得这样的极端天气变得越来越 常见——并且由此产生的影响将不仅危及老人和病人。据近期报道，气候变暖不仅对生命直接产生威胁，这些气候变化还会引起几亿个小时的劳动力损失，增强感染性疾病的传播条件，以及减少作物的产量。', 'www.google.com'),
  new News('El cambio climático está teniendo un impacto importante sobre la Salud Global', '气候变化正对全球健康产生巨大影响', 'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.', '2019/03/17', 'DELE A2', '235', 'Scientific American',
      'Una devastadora ola de calor que azotó Europa en 2003, matando a decenas de miles de personas, estiman los científicos. Muchos eran mayores, con movilidad reducida, y algunos ya padecían enfermedades crónicas.\nPero el cambio climático está haciendo tales extremas más frecuentes, y los efectos no se limitan al viejo y enfermo. Las temperaturas de calentamiento no sólo amenazan vidas directamente.\nTambién causar miles de millones de horas de trabajo perdida, mejorar las condiciones para la propagación de enfermedades infecciosas y reducir el rendimiento de los cultivos, según un informe reciente.\nEl informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.\nAfecta a todo el mundo todo el mundo, cada persona, cada población individual. Ningún país es inmune", dice Nick Watts, director ejecutivo de la cuenta regresiva de la lanceta y uno de muchos coautores del informe. "Nos hemos estado viendo estos impactos desde hace algún tiempo.\n',
      '2003年，一股毁灭性的热浪席卷了欧洲，据科学家估计，造成了成千上万的人的死亡。这其中有很多是行动不便的老年人，也有一些一直遭受慢性疾病的人。但是，气候变化正使得这样的极端天气变得越来越 常见——并且由此产生的影响将不仅危及老人和病人。据近期报道，气候变暖不仅对生命直接产生威胁，这些气候变化还会引起几亿个小时的劳动力损失，增强感染性疾病的传播条件，以及减少作物的产量。', 'www.google.com'),
];

News showingNews;

List<String> wrongAnswer = ["Que no puede contener agua de lluvia durante largo periodo de tiempo.", "Impide que la mayoría de las aguas subterráneas circulantes.", "Absorber la mayoría del agua se cintains de ríos."];

Question newsQuestion = Question("El informe, publicado el pasado mes de diciembre en la revista Lancet, representa los últimos resultados de la cuenta atrás de The Lancet, una coalición de organizaciones internacionales de investigación colaborando con la Organización Mundial de la salud y la Organización Meteorológica Mundial. El grupo de seguimiento de los impactos de la salud de y respuestas del gobierno a — el cambio climático.", "1.¿Cuál de las siguientes puede ser inferringed en el apartado 1 sobre la tierra que andamos en?", "Tiene capacidad para almacenar grandes cantidades.", wrongAnswer);